- hosts: all
  become: True
  # Connection user is set in group_vars/all.yml: ansible_user: localuser
  # We connect as localuser, then use become: True to run tasks as root
  roles:
    # System initialization
    - role: 00_init
      tags: [00_init, initial, setup]
    
    # Backup must be FIRST - create a backup before making changes
    - role: 01_backup_etc
      tags: [01_backup_etc, backup, initial]
    
    # SSH and user configuration
    - role: 02_init_sshd
      tags: [02_init_sshd, ssh, security]
    - role: 03_configure_users
      tags: [03_configure_users, users]
    
    # Basic system configuration
    - role: 04_configure_hostname
      tags: [04_configure_hostname, system]
    - role: 05_configure_sysctl_limits
      tags: [05_configure_sysctl_limits, system, performance]
    - role: 06_configure_kernel
      tags: [06_configure_kernel, system, kernel]
    - role: 07_remove_unwanted_services
      tags: [07_remove_unwanted_services, system, cleanup]
    - role: 08_configure_security
      tags: [08_configure_security, security]
    - role: 09_configure_locales
      tags: [09_configure_locales, system, locale]
    - role: 10_manage_services
      tags: [10_manage_services, system, services]
    
    # Network settings and certificates
    - role: 11_certificates
      tags: [11_certificates, security, certificates]
    - role: 12_date_timezone
      tags: [12_date_timezone, system, time]
    - role: 13_configure_repo
      tags: [13_configure_repo, packages, repo]
    - role: 14_install_software
      tags: [14_install_software, packages]
    
    # Additional configuration
    - role: 15_configure_bash
      tags: [15_configure_bash, shell, bash]
    - role: 16_configure_network
      tags: [16_configure_network, network]
    
    # Final steps - update and reboot must be LAST
    - role: 17_update_reboot
      tags: [17_update_reboot, final, update, reboot]
